###Consider the below code to answer further questions:
```
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
```
##Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

* Yes, there is a difference in the data type of variables list_ and array_list. The variable list_ is a Python list while the variable array_list is a NumPy array.

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


##Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# print data type of each element in list_
for elements in list_:
    print(type(elements))

# print data type of each element in array_list
for elem in array_list:
    print(type(elem))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


##Q3. Considering the following changes in the variable, array_list:
```
array_list = np.array(object = list_, dtype = int)
```
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

##Ans --> 
* Yes, there will be a difference in the data type of the elements present in both the variables list_ and array_list when array_list is defined as np.array(object=list_, dtype=int). The dtype parameter is used to specify the data type of the array elements.

* In this case, the dtype parameter is set to int, which means that the elements in array_list will be converted to integers.

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# print data type of each element in list_
for elem in list_:
    print(type(elem))

# print data type of each element in array_list
for elem in array_list:
    print(type(elem))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Consider the below code to answer further questions:
```
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
```
##Q4. Write a code to find the following characteristics of variable, num_array:
#(i) shape


In [4]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# find shape of num_array
print(num_array.shape)  




(2, 3)


#(ii) size

In [5]:
# find size of num_array
print(num_array.size)   

6


##Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.


In [6]:
import numpy as np

# create 3x3 NumPy array with zeros
zeros_array = np.zeros((3, 3))

# print zeros_array
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


##Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [7]:
import numpy as np

# create identity matrix of shape (5, 5)
identity_matrix = np.identity(5)

# print identity_matrix
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
